export enum ActionTypes {
  LOAD_START = 'LOAD_START',
  LOAD_FINISH = 'LOAD_FINISH',
  LOAD_NEWS = 'LOAD_NEWS',
  SET_NEWS = 'SET_NEWS',
  RESET_NEWS = 'RESET_NEWS',
  LOAD_NEWS_PAGE = 'LOAD_NEWS_PAGE',
  SET_NEWS_PAGE = 'SET_NEWS_PAGE',
  LOAD_COMMENTS = 'LOAD_COMMENTS',
  SET_COMMENTS = 'SET_COMMENTS',
  LOAD_NESTED_COMMENTS = 'LOAD_NESTED_COMMENTS',
  SET_NESTED_COMMENTS = 'SET_NESTED_COMMENTS'
}
